In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [3]:
# Load the data
df_sst = pd.read_csv('dataset/sst.csv', skiprows=[1])
df_dhw = pd.read_csv('dataset/dhw.csv', skiprows=[1])

In [4]:
df_sst.head()

                   time  latitude  longitude  analysed_sst
0  2023-02-08T12:00:00Z     8.875     79.525         27.33
1  2023-02-09T12:00:00Z     8.875     79.525         27.36
2  2023-02-10T12:00:00Z     8.875     79.525         27.44
3  2023-02-11T12:00:00Z     8.875     79.525         27.56
4  2023-02-12T12:00:00Z     8.875     79.525         27.38

In [5]:
df_dhw.head()

                   time  latitude  longitude  degree_heating_week
0  2023-02-02T12:00:00Z     8.875     79.525                  0.0
1  2023-02-03T12:00:00Z     8.875     79.525                  0.0
2  2023-02-04T12:00:00Z     8.875     79.525                  0.0
3  2023-02-05T12:00:00Z     8.875     79.525                  0.0
4  2023-02-06T12:00:00Z     8.875     79.525                  0.0

In [6]:
# Merge and Clean
df = pd.merge(df_sst, df_dhw, on=['time', 'latitude', 'longitude'])
df['time'] = pd.to_datetime(df['time'])

In [7]:
df.head()

                       time  latitude  ...  analysed_sst  degree_heating_week
0 2023-02-08 12:00:00+00:00     8.875  ...         27.33                  0.0
1 2023-02-09 12:00:00+00:00     8.875  ...         27.36                  0.0
2 2023-02-10 12:00:00+00:00     8.875  ...         27.44                  0.0
3 2023-02-11 12:00:00+00:00     8.875  ...         27.56                  0.0
4 2023-02-12 12:00:00+00:00     8.875  ...         27.38                  0.0

[5 rows x 5 columns]

In [8]:
# Convert time to "Days since start"
df['days'] = (df['time'] - df['time'].min()).dt.days

In [9]:
# Normalize the data (Neural Networks love numbers between 0 and 1)
scaler_temp = MinMaxScaler()
scaler_time = MinMaxScaler()

t_data = scaler_time.fit_transform(df[['days']])
temp_data = scaler_temp.fit_transform(df[['analysed_sst']])

In [10]:
df.head()

                       time  latitude  ...  degree_heating_week  days
0 2023-02-08 12:00:00+00:00     8.875  ...                  0.0  2922
1 2023-02-09 12:00:00+00:00     8.875  ...                  0.0  2923
2 2023-02-10 12:00:00+00:00     8.875  ...                  0.0  2924
3 2023-02-11 12:00:00+00:00     8.875  ...                  0.0  2925
4 2023-02-12 12:00:00+00:00     8.875  ...                  0.0  2926

[5 rows x 6 columns]